### ISSUE TITLE
validation problem

### ISSUE THREAD

**Issue by radityaIch** [pandemuliada/InventarisApp#1]
yeah... it's look good but ... when i open dashboard.php without login it doesn't redirect me to login.php... so i see the error session in dashboard because i'm not logging in........but when i opened class/authentication.php it has a validation to redirect to login.php and it doesn't work

```
`public function __construct() {
      parent::__construct();
      if (!isset($_SESSION['user'])) {
        $_SESSION['user'] = 'something';
        header('Location: ' . BASE_URL . '/login.php');
      }
    }`
```

can you solve this problem?

sorry for bad english :-)

**Comment by radityaIch** [comment]
I have solved the problem...... It just modify a little bit in the dashboard.php

On the below line 2 give this code: 

`If($_SESSION['user'] == 'something'){
header('location:'.BASE_URL.'/login.php');
}
else{
.......
}`

And it's worked XD

**Comment by pandemuliada** [comment]
Nice, thank you
